[package]
name = "aoc"
version = "0.1.0"
edition = "2021"
default-run = "aoc"

[dependencies]
"aoc_utils" = { path="../aoc_utils" }
"clap" = { version = "4.5.21", features=["derive"] }

[[bin]]
name = "aoc"

[[bin]]
name = "data_downloader"
