[package]
name = "aoc_data_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
scraper = "0.21.0"
"clap" = { version = "4.5.21", features = ["derive"] }
argfile = "0.2.1"
"aoc_utils" = { path="../aoc_utils" }
